[package]
name = "nevo-quad-world"
version.workspace = true
edition.workspace = true

[dependencies]
nevo-core.workspace = true
nevo-utils.workspace = true
rand = { workspace = true, features = ["small_rng"] }
rand_distr.workspace = true
glam.workspace = true
candle.workspace = true
candle-nn.workspace = true
anyhow.workspace = true
eframe.workspace = true
