[package]
name = "nevo_nn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_distr = "0.4.3"
ndarray = "0.15.4"
nevo_core = { path = "../nevo_core" }
