[package]
name = "bacteria"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vecmat = "0.7"
ndarray = "0.15"
eframe = "0.18"
nevo = { path = "../nevo" }
